# Generated by Django 3.1 on 2020-09-03 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0007_book_material_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(0, 'Uploaded'), (1, 'Processed')], default=0, max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('material_type', models.CharField(choices=[('Book', 'Book'), ('Lecture', 'Lecture'), ('Assignment', 'Assignment')], default='None', max_length=20)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
