# Generated by Django 3.1 on 2020-11-04 21:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('upload', '0008_auto_20200903_1750'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
