# Generated by Django 3.1.2 on 2020-10-18 06:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_publication', models.DateField(help_text='Date of publication')),
                ('title', models.CharField(help_text='Title of book', max_length=50)),
                ('author', models.CharField(help_text='Author', max_length=50)),
                ('file', models.FileField(help_text='File with material', upload_to='')),
                ('file_name', models.CharField(help_text='Name of file', max_length=50)),
                ('visibility', models.CharField(choices=[('0', 'Uploaded'), ('1', 'Processed')], default='0',
                                                help_text='state of book', max_length=1)),
                ('tags', models.ManyToManyField(help_text='Tags of book', to='search.Tag')),
            ],
        ),
    ]
